### PR TITLE
Add synchronous implementation Arp.Lookup()

### PR DESCRIPTION
**Pull request by energywave**
I've added synchronous implementation of the required methods to create a synchronous Lookup() method.
I've also created a TryLookup() method that returns a bool that indicate if the lookup was successful or not, returning the mac in the out argument, as per .net standard implementation. It's handy :)

### CODE REVIEW

**Comment by georg-jung** [comment]
Thanks for your contribution! Also, sorry for the delay in reviewing. I think adding sync implementations can be a benefit to consumers that are bound to using sync code. Sadly, when I originally created the lib, I didn't stick to the `*Async` naming best practices. Thus, this is a breaking change and will require us to release a `v2.x`.

* I improved the project's structure (i.e. added automatic versioning using NBGV) and rebased your PR on top of that
* I changed the version number (using nbgv's `version.json`) to 2.x
* I removed the TryLookup method/commit:
  * Imho, in the spirit of the framework's Try* methods, Try* methods should be offered in cases were the operation itself can be tried, without catching exceptions. Like `someTask.Result` would be a sync-over-async implementation and I would leave it up to the consumer if that behaviour is wanted, I'd tend to only add Try* methods were trying is intrinsically possible. I.e. when consuming code on a hot path, I, as a consumer, would probably use a Try* method because I would assume it is faster than doing the operation in a `try`-block and `catch`ing if needed. A catching Try* implementation can thus be misleading imho (and provides no too substantial benefit), which is why I would leave implementing one up to the consumer.

I hope you agree with what I did here. If you think my changes are fine, I'd be happy to merge this soon and push a new version to nuget.

**Comment by georg-jung** [comment]
Hope it's okay I rebased your work at this point. Would have probably been nicer to discuss first, as I removed the Try* method, sorry. If you think my reasoning is faulty we can of course discuss that :).

For reference, the method:

	/// <summary>
	/// This method try to get or lookup for the MAC address that corresponds to the specified IP address. If the MAC address is found it's passeed in the out mac argument and returned true.
	/// If the MAC address isn't found for whatever reason the mac will be null and returned false.
	/// </summary>
	/// <param name="ip">The IP address for wich you want to get the MAC address for</param>
	/// <param name="mac">This reference argument will contain the MAC address of the specified IP if found, otherwise null</param>
	/// <returns>Returns if the MAC of the specified IP cound be found and is returned in the reference argument mac</returns>
	public static bool TryLookup(IPAddress ip, out PhysicalAddress mac)
	{
		try
		{
			mac = Lookup(ip);
			return true;
		}
		catch 
		{
			mac = null;
			return false;
		}
	}

**Comment by energywave** [comment]
Thank you Georg, no problem for delay, we are all working for the glory here :) And don't worry about having removed the Try method, we still have space for discussing it (below). The project is yours so yours is the right to decide :)
I thank you for the library (very useful!) and for your efforts in review my code to ensure quality in your releases, that's great.
I'll reply to some of your statements.

> Sadly, when I originally created the lib, I didn't stick to the `*Async` naming best practices. Thus, this is a breaking change and will require us to release a `v2.x`.

Well, the only class supposed to be used by the user is the static Arp class. And methods there had *Async suffix already.
Async was missing in LinuxLookupService that's an internal class so no exposing of public methods in the interface.
In my point of view no need for a v2.x as in the public interface there only are two more methods (well, one :( ), nothing more.
 
> * I improved the project's structure (i.e. added automatic versioning using NBGV) and rebased your PR on top of that
> * I changed the version number (using nbgv's `version.json`) to 2.x

Well done, I don't know NBGV as I rarely pushing code to GitHub (if only I had more time...)

> * I removed the TryLookup method/commit:
>   
>   * Imho, in the spirit of the framework's Try* methods, Try* methods should be offered in cases were the operation itself can be tried, without catching exceptions. Like `someTask.Result` would be a sync-over-async implementation and I would leave it up to the consumer if that behaviour is wanted, I'd tend to only add Try* methods were trying is intrinsically possible. I.e. when consuming code on a hot path, I, as a consumer, would probably use a Try* method because I would assume it is faster than doing the operation in a `try`-block and `catch`ing if needed. A catching Try* implementation can thus be misleading imho (and provides no too substantial benefit), which is why I would leave implementing one up to the consumer.

I think that Try* methods must have the following features:
* Don't throw exceptions
* Return a bool value telling if the operation was successful
* If the return value is true then you can access the out argument with the result of the operation
* There is a method with same name but without Try that let me use the code and handle by myself the try catch.

In fact I totally agree with this answer on [Stackoverflow](https://stackoverflow.com/a/17207748/4690604)
And based on those point the TryLookup method meets all the assumptions.
The implementation was born because using the Lookup method in my code there was more than one way that the operation could fail so a Try* method to a binary operation to know if the operation was successful or not in one single row was very handy. Andy why to implement it in my code when I can share handy code with other people ;)
We can further discuss this, if you want.
 
> I hope you agree with what I did here. If you think my changes are fine, I'd be happy to merge this soon and push a new version to nuget.

I agree too all, as said it's your project :) I'm only sad about the TryLookup method but I can survive :)

**Comment by georg-jung** [comment]
> In my point of view no need for a v2.x as in the public interface there only are two more methods (well, one :( ), nothing more.

Oh, obviously you're right here and I was mistasken earlier. Thanks for pointing that out! I removed the version increment. Sorry about the confusion.

Also, I started #9 to avoid these mistakes in future (when dotnet 6 is released).

> Well done, I don't know NBGV as I rarely pushing code to GitHub (if only I had more time...)

Just in case that might be useful for you: I tend to use [NBGV](https://github.com/dotnet/Nerdbank.GitVersioning/) in quite many of my more recent projects (even desktop apps and the like, although it's not specifically built for that) because I find it really practical. It doesn't require GitHub but just relys on git itself.

> In fact I totally agree with this answer on Stackoverflow

Thanks, I think that question is a good ressource for reasoning here. I totally agree with the answer you linked and think those 4 points are perfectly valid and are also in line with my gut feeling about Try* methods. Nevertheless, I think the [accepted answer](https://stackoverflow.com/a/17207813/1200847) to that question is also in line with my gut feeling, that Try* methods are not meant to be just `try-catch` wrappers. Reviewing the corresponding [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance) (linked on SO) yields:

> CONSIDER the Try-Parse Pattern for members that might throw exceptions in common scenarios to avoid performance problems related to exceptions.

I feel that supports my idea that providing a Try* method makes consumers think this path is faster as it doesn't involve throwing and catching - which would be false in our case, but true for all cases in the dotnet runtime. Given how simple a catching Try* is to implement, I'll prefer not making it part of the library. Of course, if there is a way of implementing it, that doesn't involve "just" catching, I'm more than happy to consider that.

**Comment by georg-jung** [comment]
See https://www.nuget.org/packages/ArpLookup/1.2.14 and https://github.com/georg-jung/ArpLookup/releases/tag/v1.2.14

**Comment by energywave** [comment]
> Also, I started #9 to avoid these mistakes in future (when dotnet 6 is released).

Again as I don't use Github that's all new here for me but seems interesting and thank you for pointing out, that's all resources useful to learn something new :)

> I feel that supports my idea that providing a Try* method makes consumers think this path is faster as it doesn't involve throwing and catching - which would be false in our case, but true for all cases in the dotnet runtime. Given how simple a catching Try* is to implement, I'll prefer not making it part of the library. Of course, if there is a way of implementing it, that doesn't involve "just" catching, I'm more than happy to consider that.

In fact I have to say you're right. The form of the method was right but the implementation was poor and "too quick". The correct way should be to handle differently the api result by not throwing exceptions. I've seen the implementation of various TryParse methods in the framework (by using ILSpy, I love that tool...) and they all have complex code to validate the operation and they fail without throwing exceptions.
So yes, I think I'll try again the implementation of the TryLookup method (as I find it very handy) but this time without exceptions catching.
Thank you for discussing that matter with me, it's always enriching to speak in constructive spirit!
We will hear in a new PR ;)

Oh, last but not least: you're a gentlemen. You preserved me as a second author. I'll implement in a clean way that method to deserve the author inclusion.

**Comment by georg-jung** [comment]
While I like the idea of a "real" Try* method, I'm not sure it's worth the effort of creating and maintaining one. Maybe I'm missing something, but I got the feeling it would be sensible to first (before investing too much effort) ask ourselves *why* we would want to add such method:

1. The typical motivation for a Try* method would be efficiency/speed up on hot paths. That makes sense when throwing and catching exceptions becomes a bottleneck because it happens thousands of times per second. In that case, the exception handling consumes much more (cpu) time than whatever the method does intrinsically. That's the case for all the `TryParse` methods. Parsing can be really fast when compared to throwing and catching.
2. As far as I understand, your motivation for a Try* method is mainly that it makes it easier for you to consume it.

While I guess it will be difficult to implement a non-throwing variant either way[0], I think a TryLookup doesn't make sense when looking at my first point. In every case (maybe I'm missing something, but at least in most cases) the Lookup method throws, it did some I/O operation before. It probably sent something out on the network. That I/O operation is probably by far slower than throwing and catching exceptions though. Thus, having a non-throwing variant wouldn't lead to any major speedup, thus defeating the whole purpose of a "done-right" non-throwing variant.

So, if I'm not mistaken (please correct me if I'm wrong), achieving (1) is probably impossible/doesn't make too much sense, because exception handling isn't the bottlneck here. For achieving (2) on the other hand, the implementation you had above is perfectly fine - it's just "not the library's task", in terms of separation of concerns/public interface/..., to provide such try-catch-wrapper. However, just taking the code you had and placing it in the codebase of your application is probably a great idea, as it achieves your goals and is very simple and cheap too (I mean, the code is even already written...).

Don't get me wrong, I really encourage your willingness to contribute such implementation! I just want to make sure we don't use our time on an implementation that is non-trivial and doesn't really fit our needs (again, if my assumption of *our needs* is wrong please complain!).

[0]: I guess some of the functions we call don't have Try* variants. Thus, there is no way to call them non-throwing. We would need to catch there, no matter what. The reason why there are no Try* methods for i.e. file or network IO operations is probably exactly what I wrote in (1).

**Comment by energywave** [comment]
Sorry for delay.
Yes, again you're right. I'm with you in the theory behind those arguments.
And yes, point 1 will be difficult to achieve but maybe not so difficult. For Windows, for instance, che call to the API can be done directly evaluating the result by not throwing exceptions. It's true that in case an ARP request will be sent that will be by far more time consuming than the exception but the doc of that API says that in case that the MAC is already in the ARP list that will be sent to the caller without sending a real ARP request. In that case the Exception throwing will be more time consuming than api execution.
Sorry, I didn't evaluate what happens in Linux as I'm more focused on Windows.

However my motivation to implement it is because the Lookup method can exit with a thrown exception in case the specified IP is not in the local ARP list and the ARP request will not have a reply.
That is handled with a Win32Exception. But then a user calling Lookup method will questions itself "what other exceptions can be thrown that I have to manage here? What exceptions will be thrown, for example, if I run the code on Linux?" a far more simple solution for the user was to have a TryLookup method that exits with a true or false, without the need for the user to setup a try catch handling different exceptions that he don't knows (as they're not documented).

This was my instinct as a user of your library at first. So I implemented the TryLookup method so that other users could find it straightforward to use it with a predictable result when in need of a MAC address.

I can implement the TryLookup handling "normal" errors like the one told above without try catcing.
Another option could be to handle the result of the Windows API when the MAC is not found and return a null value, instead of throwing an exception.
After all an Exception should be an exceptional error that is not handled by the called code or throwed by that code to signal an anomaly. Not finding the MAC of the provided IP is not an anomaly, it seems to me a common result so even that option is viable for me.

Or maybe we can do both :)

What are your thoughts?

**Comment by georg-jung** [comment]
I consider Linux and Windows equally important, given the cross-platform compatibility is one of our core features. I think implementing a Try* on Linux will be more difficult, as the underlying APIs don't provide Try* methods.

However, I think you have a really good point when you say 

> After all an Exception should be *an exceptional error* that is not handled by the called code or throwed by that code to signal an anomaly. *Not finding the MAC of the provided IP is not an anomaly, it seems to me a common result* so even that option is viable for me.

Actually, this is exactly what happens if we don't find a result on Linux (and what is documented too, ugh). Just on Windows, if [SendARP returns `ERROR_BAD_NET_NAME`](https://docs.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-sendarp), we throw an exception as we consider this error code an error. That even leads to inconsistent behaviour in Linux vs Windows: not found --> `null` vs throw.

Thus, I think what we should do:

* Change the existing non-Try* method on Windows side to handle the specific `ERROR_BAD_NET_NAME` error code so that we return null then.
* Don't change anything about the other error codes as they are "really exceptional".
* Don't add any Try* methods.

(Note that this is a breaking change and requires us to release a 2.0.)

Given this removes the exception from the "most common exceptional" or "not really exceptional" case, does this suit your needs? I think it would be a good idea either and it is really something I overlooked until now.

**Comment by energywave** [comment]
Ok Georg, this is a good compromise :) Handling ERROR_BAD_NAME error code in method returning null value as the Linux implementation will be the most consistent solution.

**Comment by energywave** [comment]
I totally agree with you :)

**Comment by georg-jung** [comment]
See https://github.com/georg-jung/ArpLookup/releases/tag/v2.0.3 and https://www.nuget.org/packages/ArpLookup/2.0.3

**Comment by energywave** [comment]
Looks good to me. Good work Georg! I'll revert my project to use the new 2.0.3 version from my forked one... :)

**Pull request merged**
